print("Patient Health Data Analysis")
print_ages = [25,34,42,51,29,63,47,38,56,31]
average_age = sum(patient_ages)/len(patient_ages)
print("Average patient age:",average_age)
youngest_age = min(print_ages)
oldest_age = max(print_ages)
print("Youngest patient age:",youngest_age)
print("Oldest patient age:",oldest_age)
number_of_patients = len(print_ages)
print("Total number of patients:",number_of_patients)
